# Generated by Django 5.0 on 2024-01-03 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sagird_adi', models.CharField(max_length=50)),
                ('sagird_soyadi', models.CharField(max_length=50)),
                ('sagird_yasi', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SinifAdres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif', models.IntegerField(max_length=5)),
                ('adres', models.CharField(max_length=100)),
                ('sinifAdres_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e.sinif')),
            ],
        ),
    ]
