# Generated by Django 5.0 on 2024-01-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e', '0002_alter_sinif_sagird_yasi_alter_sinifadres_sinif'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinif',
            name='ata',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
