# Generated by Django 5.0 on 2024-01-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e', '0003_sinif_ata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinif',
            name='ata',
        ),
        migrations.CreateModel(
            name='father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('sagird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e.sinif')),
            ],
        ),
    ]
