# Generated by Django 5.0 on 2024-01-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e', '0004_remove_sinif_ata_father'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='sinifadres',
            name='sinifAdres_id',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e.reporter')),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
        migrations.DeleteModel(
            name='father',
        ),
        migrations.DeleteModel(
            name='Sinif',
        ),
        migrations.DeleteModel(
            name='SinifAdres',
        ),
    ]
