# Generated by Django 5.0 on 2023-12-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='history',
            field=models.DateField(auto_now=True),
        ),
    ]
