# Generated by Django 5.0 on 2023-12-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
