# Generated by Django 5.0 on 2023-12-29 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0005_erp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='a2.table')),
            ],
        ),
    ]
